apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-credentials
  namespace: iac
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: cluster-secrets-store
    kind: ClusterSecretStore
  target:
    name: aws-credentials
    template:
      data:
        credentials: |
          [default]
          aws_access_key_id = {{ `{{ .accessKeyId }}` }}
          aws_secret_access_key = {{ `{{ .secretAccessKey }}` }}
  data:
    - secretKey: accessKeyId
      remoteRef:
        key: aws-credentials
        property: access-key-id
    - secretKey: secretAccessKey
      remoteRef:
        key: aws-credentials
        property: secret-access-key
