apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: ClusterSecretStore
  target:
    name: operator-oauth
  data:
    - secretKey: client_id
      remoteRef:
        key: {{ .Values.remoteKey }}
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: {{ .Values.remoteKey }}
        property: client_secret
