apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-api-secret
  namespace: kargo
spec:
  refreshInterval: 5m
  secretStoreRef: {name: {{ .Values.secretStore }}, kind: ClusterSecretStore}
  target: {name: kargo-api-secret}
  data:
    - secretKey: ADMIN_ACCOUNT_PASSWORD_HASH
      remoteRef: {key: kargo, property: admin-password-hash}
    - secretKey: ADMIN_ACCOUNT_TOKEN_SIGNING_KEY
      remoteRef: {key: kargo, property: admin-token-signing-key}
